import React, { createContext, useContext, useState, useEffect } from 'react';

export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', speechCode: 'en-IN' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी', speechCode: 'hi-IN' },
  { code: 'kht', name: 'Khortha / Nagpuri', native: 'खोरठा / नागपुरी', speechCode: 'hi-IN' },
  { code: 'sat', name: 'Santhali / Tribal', native: 'संताली (Santali)', speechCode: 'hi-IN' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', speechCode: 'bn-IN' }
];

const TRANSLATIONS = {
  en: {
    // Brand & Header
    platformTitle: 'SamasyaSetu',
    platformSubtitle: 'Problem-to-Solution Platform',
    sihBannerTitle: 'Jharkhand SIH Edition • Societal Innovation Collaboration Portal',
    sihBannerSubtitle: 'Connecting Citizens & PRIs with Higher Education & Industry',
    oneClickSwitcher: '1-Click Role Switcher',
    publicImpactWall: 'Public Impact Wall',
    myDashboard: 'My Dashboard',
    reportProblem: 'Report Problem',
    signIn: 'Sign In',
    register: 'Get Started',
    logout: 'Log Out',
    selectLanguage: 'Language',

    // Home / Impact Wall
    heroTag: 'Jharkhand Societal Innovation Wall',
    heroTitle: 'Transforming Citizen Challenges into Grassroots Innovation',
    heroSubtitle: 'Real-world challenges reported by citizens and PRIs, engineered by University Researchers & Startups, funded by CSR, and verified by State Administration.',
    citizensBenefited: 'Citizens Benefited',
    problemsSolved: 'Problems Solved & Deployed',
    patentsFiled: 'Patents & IP Registered',
    startupsIncubated: 'Startups Incubated',
    verifiedImpactStories: 'Verified Grassroots Impact Stories',
    statewideExplorer: 'Statewide Public Challenge Explorer',
    deployedInnovation: 'Deployed Innovation',
    communityOutcome: 'Community Outcome',
    citizensImpacted: 'Citizens Impacted',

    // Citizen Dashboard & Report
    welcomeUser: 'Welcome',
    citizenPortalTag: 'Citizen & Community Portal (Jharkhand SIH)',
    citizenPortalDesc: 'Report local civic or rural challenges, track verification status, and connect directly with Higher Education Institutions and startups building solutions.',
    reportNewProblem: 'Report a New Problem',
    trackMyReports: 'Track My Reports',
    myReportsLogged: 'My Reports Logged',
    activeChallenges: 'Active Challenges',
    solutionsInField: 'Solutions in Field',
    impactVerified: 'Impact Verified',
    recentSocietalReports: 'Recent Societal Reports',
    sortedByPriority: 'Sorted by explainable priority',
    viewDetails: 'View Details',
    confirmationsCount: 'Confirmations',
    proposalsCount: 'Proposals',
    noReportsYet: 'No Problems Reported Yet',
    noReportsYetDesc: "You haven't submitted any civic or societal issues yet. Report a problem in your neighborhood to engage university innovators.",
    reportFirstProblem: 'Report Your First Problem',
    progressLifecycle: 'Progress Lifecycle',
    reportedOn: 'Reported on',

    // Report Form
    step1Title: '1. Problem Description & Regional Language Support',
    step2Title: '2. Location & Geographic Coordinates',
    step3Title: '3. Photo / Video Evidence & Supporting Documents',
    problemTitleLabel: 'Problem Title *',
    problemTitlePlaceholder: 'e.g. Severe Fluoride & Arsenic in Handpumps / Broken Bridge across Stream',
    problemDescLabel: 'Detailed Description (Hindi, English, or Regional) *',
    problemDescPlaceholder: 'Describe the problem, number of families affected, and current health/safety risks... (You can type in Hindi/English or click Voice-to-Text)',
    voiceToText: 'Voice-to-Text',
    recordingVoice: 'Recording voice (Speak now)...',
    autoGps: 'Auto-Capture My GPS Location',
    districtLabel: 'District (Jharkhand)',
    latitude: 'Latitude',
    longitude: 'Longitude',
    evidenceUpload: 'Photo / Video Evidence & Supporting Documents',
    uploadClickText: 'Click to upload photos / field video',
    uploadFormatsText: 'Supports JPG, PNG, MP4 up to 10MB each',
    submitAndLaunchAI: 'Submit Problem & Launch AI Analysis',
    iHaveThisProblemToo: 'I have this problem too',
    confirmedBy: 'Confirmed',
    submitSolutionProposal: 'Submit Solution Proposal',
    englishTranslation: 'English Translation (AI Pipeline)',
    originalSubmission: 'Original Report / Regional Submission',
    aiPipelineInProgress: 'AI Pipeline in progress: Translating regional text, classifying domain themes, and computing explainable priority scores...',

    // Problem Detail
    reportedBy: 'Reported by',
    solutionsAndProposals: 'Solutions & Innovation Proposals',
    noProposalsYet: 'No Solution Proposals Yet',
    noProposalsDesc: 'This challenge is currently open for proposals from Universities, Colleges, Startups, and MSMEs.',
    beFirstToSubmit: 'Be the first to submit a solution',
    techApproachLabel: 'Technical Approach & Deployment Architecture',
    budgetLabel: 'Estimated Budget',
    timelineLabel: 'Timeline',
    csrFundingPledged: 'CSR Funding Pledged',
    problemLocation: 'Problem Location',
    photoFieldEvidence: 'Photo & Field Evidence',
    aiMatchedInstitutions: 'AI-Matched Institutions',

    // Priorities
    priorityEngine: 'Explainable Priority Engine',
    criticalPriority: 'Critical Priority',
    highPriority: 'High Priority',
    mediumPriority: 'Medium Priority',
    lowPriority: 'Low Priority',
    safetyRisk: 'Safety / Hazard Risk',
    citizenVolume: 'Citizen Reports Volume',
    schoolClinicProximity: 'School/Clinic Proximity',
    daysPending: 'Days Pending Age',
    districtTier: 'Jharkhand District Aspirational Tier',
    scoreBreakdown: 'Score Composition Breakdown:',
    auditTrail: 'Audit Trail:',

    // Status
    statusProcessing: 'AI Processing',
    statusPendingVerification: 'Pending Admin Verification',
    statusPublished: 'Published & Open for Solutions',
    statusClaimed: 'Solution Proposed',
    statusInDevelopment: 'In Development',
    statusDeployed: 'Deployed in Field',
    statusImpactVerified: 'Impact Verified & Solved',
    statusRejected: 'Rejected',
    statusMerged: 'Merged (Duplicate)',

    // Admin
    adminCommandCenter: 'State Administrative Command Center • Jharkhand',
    adminDesc: 'Review AI-analyzed citizen reports, approve new administrative registrations, and monitor statewide innovation metrics.',
    verificationQueueTab: 'Problem Verification Queue',
    accountApprovalsTab: 'Govt/Admin Account Approvals',
    analyticsTab: 'Statewide Analytics',
    oneClickApprove: '1-Click Approve & Publish',
    reject: 'Reject',
    approveAccount: 'Approve Account',
    verificationQueueClear: 'Verification Queue is Clear',
    verificationQueueClearDesc: 'All citizen reports have been verified or processed. New submissions will appear here automatically.',
    noPendingAccounts: 'No Pending Account Approvals',
    noPendingAccountsDesc: 'All administrative and government department accounts have been verified.',

    // Institution & Industry
    heiPortalTag: 'Higher Education Institution & Student Innovation Portal',
    heiDesc: "Explore AI-matched societal problems tailored to your institute's department expertise, build multi-disciplinary student teams, and log verified field impact.",
    matchedChallengesTab: 'Matched Challenges',
    myProjectsTab: 'My Projects & Milestones',
    claimAndPropose: 'Claim Challenge & Propose Solution',
    techApproach: 'Technical Approach & Solution Architecture *',
    techStack: 'Tech Stack / Tools *',
    estimatedBudget: 'Estimated Budget (₹ INR)',
    timelineWeeks: 'Timeline (Weeks)',
    milestonesRoadmap: 'Project Milestones Roadmap',
    logImpactAndIP: 'Log IP / Patent & Impact',
    csrGrantPledge: 'Pledge CSR Grant & Mentorship',
    noMatchedOpen: 'No Open Challenges Available',
    noMatchedOpenDesc: 'All open problems matching your domain tags are currently under development or completed.',
    noActiveClaimed: 'No Active Projects Claimed',
    noActiveClaimedDesc: 'Your organization has not claimed any societal challenges yet. Browse the Matched Challenges Feed.',

    // Auth
    signInTab: 'Sign In',
    createAccountTab: 'Create Account',
    emailOrPhone: 'Email or Phone Number',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    signInButton: 'Sign In to Portal',
    registeringAs: 'I am registering as a:',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    emailAddress: 'Email Address',
    confirmPassword: 'Confirm Password',
    completeRegistration: 'Complete Registration'
  },

  hi: {
    // Brand & Header
    platformTitle: 'समस्यासेतु',
    platformSubtitle: 'समस्या से समाधान मंच',
    sihBannerTitle: 'झारखंड एसआईएच संस्करण • सामाजिक नवाचार सहयोग पोर्टल',
    sihBannerSubtitle: 'नागरिकों और पंचायतों को उच्च शिक्षण संस्थानों व उद्योग से जोड़ना',
    oneClickSwitcher: '1-क्लिक भूमिका बदलें',
    publicImpactWall: 'सार्वजनिक प्रभाव दीवार',
    myDashboard: 'मेरा डैशबोर्ड',
    reportProblem: 'समस्या दर्ज करें',
    signIn: 'लॉग इन करें',
    register: 'शुरू करें',
    logout: 'लॉग आउट',
    selectLanguage: 'भाषा',

    // Home / Impact Wall
    heroTag: 'झारखंड सामाजिक नवाचार प्रभाव दीवार',
    heroTitle: 'नागरिक समस्याओं को जमीनी नवाचार में बदलना',
    heroSubtitle: 'नागरिकों और पंचायतों द्वारा उठाई गई चुनौतियां, विश्वविद्यालयों और स्टार्टअप्स द्वारा विकसित समाधान, सीएसआर द्वारा वित्तपोषित और सरकार द्वारा सत्यापित।',
    citizensBenefited: 'लाभान्वित नागरिक',
    problemsSolved: 'सुलझाई गई समस्याएं',
    patentsFiled: 'पेटेंट और बौद्धिक संपदा',
    startupsIncubated: 'शुरू हुए स्टार्टअप्स',
    verifiedImpactStories: 'सत्यापित सफल नवाचार कहानियां',
    statewideExplorer: 'राज्यव्यापी सार्वजनिक समस्या मानचित्र',
    deployedInnovation: 'मैदान में स्थापित नवाचार',
    communityOutcome: 'सामुदायिक परिणाम',
    citizensImpacted: 'नागरिक लाभान्वित',

    // Citizen Dashboard & Report
    welcomeUser: 'स्वागत है',
    citizenPortalTag: 'नागरिक एवं समुदाय पोर्टल (झारखंड SIH)',
    citizenPortalDesc: 'अपनी स्थानीय नागरिक या ग्रामीण समस्या दर्ज करें, समाधान की स्थिति ट्रैक करें और विश्वविद्यालयों तथा स्टार्टअप्स से जुड़ें।',
    reportNewProblem: 'नई समस्या दर्ज करें',
    trackMyReports: 'मेरी दर्ज समस्याएं देखें',
    myReportsLogged: 'मेरी कुल शिकायतें',
    activeChallenges: 'सक्रिय चुनौतियाँ',
    solutionsInField: 'मैदान में कार्यरत समाधान',
    impactVerified: 'सत्यापित समाधान',
    recentSocietalReports: 'हालिया सामाजिक समस्याएं',
    sortedByPriority: 'पारदर्शी प्राथमिकता के आधार पर व्यवस्थित',
    viewDetails: 'विवरण देखें',
    confirmationsCount: 'नागरिक पुष्टियाँ',
    proposalsCount: 'प्रस्ताव',
    noReportsYet: 'कोई समस्या अभी तक दर्ज नहीं हुई',
    noReportsYetDesc: 'आपने अभी तक कोई समस्या दर्ज नहीं की है। अपने क्षेत्र की समस्या दर्ज करें ताकि विश्वविद्यालय के छात्र व शोधकर्ता समाधान तैयार कर सकें।',
    reportFirstProblem: 'अपनी पहली समस्या दर्ज करें',
    progressLifecycle: 'प्रगति जीवनचक्र (Lifecycle)',
    reportedOn: 'दर्ज करने की तिथि',

    // Report Form
    step1Title: '1. समस्या का विवरण एवं भाषा सहायता',
    step2Title: '2. भौगोलिक स्थान एवं जीपीएस निर्देशांक',
    step3Title: '3. फोटो / वीडियो साक्ष्य और दस्तावेज़',
    problemTitleLabel: 'समस्या का शीर्षक *',
    problemTitlePlaceholder: 'जैसे: चापाकल में फ्लोराइड/आर्सेनिक की समस्या या टूटा हुआ पुल',
    problemDescLabel: 'विस्तृत विवरण (हिंदी, संताली, खोरठा या अंग्रेजी में) *',
    problemDescPlaceholder: 'समस्या, प्रभावित परिवारों की संख्या और स्वास्थ्य/सुरक्षा खतरों का विवरण लिखें... (आप बोलकर भी लिख सकते हैं)',
    voiceToText: 'बोलकर लिखें (वॉइस इनपुट)',
    recordingVoice: 'आवाज़ रिकॉर्ड हो रही है (अब बोलें)...',
    autoGps: 'मेरा जीपीएस स्थान स्वतः दर्ज करें',
    districtLabel: 'जिला (झारखंड)',
    latitude: 'अक्षांश (Latitude)',
    longitude: 'देशांतर (Longitude)',
    evidenceUpload: 'फोटो / वीडियो साक्ष्य और दस्तावेज़',
    uploadClickText: 'फोटो या वीडियो अपलोड करने के लिए क्लिक करें',
    uploadFormatsText: 'JPG, PNG, MP4 (10MB तक)',
    submitAndLaunchAI: 'समस्या दर्ज करें और एआई विश्लेषण शुरू करें',
    iHaveThisProblemToo: 'मुझे भी यह समस्या है (समर्थन करें)',
    confirmedBy: 'पुष्टि की गई',
    submitSolutionProposal: 'समाधान प्रस्ताव प्रस्तुत करें',
    englishTranslation: 'अंग्रेजी अनुवाद (एआई विश्लेषण)',
    originalSubmission: 'मूल क्षेत्रीय शिकायत विवरण',
    aiPipelineInProgress: 'एआई विश्लेषण जारी: क्षेत्रीय भाषा अनुवाद, डोमेन वर्गीकरण और प्राथमिकता स्कोर की गणना हो रही है...',

    // Problem Detail
    reportedBy: 'दर्जकर्ता',
    solutionsAndProposals: 'नवाचार समाधान एवं विश्वविद्यालय प्रस्ताव',
    noProposalsYet: 'अभी तक कोई प्रस्ताव नहीं आया',
    noProposalsDesc: 'यह चुनौती वर्तमान में विश्वविद्यालयों, कॉलेजों और स्टार्टअप्स के प्रस्तावों के लिए खुली है।',
    beFirstToSubmit: 'पहला समाधान प्रस्तुत करें',
    techApproachLabel: 'तकनीकी दृष्टिकोण एवं वास्तुकला',
    budgetLabel: 'अनुमानित बजट',
    timelineLabel: 'समय सीमा',
    csrFundingPledged: 'सीएसआर अनुदान स्वीकृत',
    problemLocation: 'समस्या का स्थान',
    photoFieldEvidence: 'फोटो एवं साक्ष्य',
    aiMatchedInstitutions: 'एआई-अनुकूलित संस्थान',

    // Priorities
    priorityEngine: 'पारदर्शी प्राथमिकता स्कोर इंजन',
    criticalPriority: 'अति-गंभीर प्राथमिकता',
    highPriority: 'उच्च प्राथमिकता',
    mediumPriority: 'मध्यम प्राथमिकता',
    lowPriority: 'सामान्य प्राथमिकता',
    safetyRisk: 'सुरक्षा / स्वास्थ्य जोखिम',
    citizenVolume: 'प्रभावित नागरिकों की संख्या',
    schoolClinicProximity: 'स्कूल/अस्पताल निकटता',
    daysPending: 'लंबित दिनों की संख्या',
    districtTier: 'आकांक्षी जिला प्राथमिकता',
    scoreBreakdown: 'स्कोर गणना विवरण:',
    auditTrail: 'ऑडिट ट्रेल (कारण):',

    // Status
    statusProcessing: 'एआई प्रोसेसिंग जारी',
    statusPendingVerification: 'प्रशासनिक सत्यापन लंबित',
    statusPublished: 'प्रकाशित एवं समाधान हेतु खुला',
    statusClaimed: 'समाधान प्रस्तावित',
    statusInDevelopment: 'विकास कार्य जारी',
    statusDeployed: 'मैदान में तैनात',
    statusImpactVerified: 'सत्यापित एवं समाधान संपन्न',
    statusRejected: 'अस्वीकृत',
    statusMerged: 'समेकित (डुप्लीकेट)',

    // Admin
    adminCommandCenter: 'राज्य प्रशासनिक कमान केंद्र • झारखंड',
    adminDesc: 'नागरिक रिपोर्टों की समीक्षा करें, नए प्रशासनिक खातों को मंजूरी दें और राज्यव्यापी नवाचार की निगरानी करें।',
    verificationQueueTab: 'समस्या सत्यापन कतार',
    accountApprovalsTab: 'विभागीय खाता अनुमोदन',
    analyticsTab: 'राज्यव्यापी विश्लेषण',
    oneClickApprove: '1-क्लिक स्वीकृत एवं प्रकाशित करें',
    reject: 'अस्वीकार करें',
    approveAccount: 'खाता स्वीकृत करें',
    verificationQueueClear: 'सत्यापन कतार खाली है',
    verificationQueueClearDesc: 'सभी नागरिक रिपोर्टों का सत्यापन हो चुका है। नई शिकायतें यहां स्वतः दिखाई देंगी।',
    noPendingAccounts: 'कोई लंबित खाता अनुमोदन नहीं है',
    noPendingAccountsDesc: 'सभी प्रशासनिक और विभागीय खाते पहले से सत्यापित हैं।',

    // Institution & Industry
    heiPortalTag: 'उच्च शिक्षण संस्थान एवं छात्र नवाचार पोर्टल',
    heiDesc: 'अपने संस्थान की विशेषज्ञता के अनुसार समस्याओं को देखें, छात्र टीमें बनाएं और जमीनी प्रभाव दर्ज करें।',
    matchedChallengesTab: 'अनुकूलित चुनौतियां',
    myProjectsTab: 'मेरी परियोजनाएं एवं मील के पत्थर',
    claimAndPropose: 'चुनौती स्वीकार करें व समाधान भेजें',
    techApproach: 'तकनीकी दृष्टिकोण एवं समाधान वास्तुकला *',
    techStack: 'उपयोग होने वाली तकनीक (Tech Stack) *',
    estimatedBudget: 'अनुमानित बजट (₹ INR)',
    timelineWeeks: 'समय सीमा (सप्ताह)',
    milestonesRoadmap: 'परियोजना मील के पत्थर (Roadmap)',
    logImpactAndIP: 'पेटेंट एवं सामाजिक प्रभाव दर्ज करें',
    csrGrantPledge: 'सीएसआर अनुदान व मार्गदर्शन प्रदान करें',
    noMatchedOpen: 'कोई खुली चुनौती उपलब्ध नहीं है',
    noMatchedOpenDesc: 'आपकी डोमेन विशेषज्ञता से मेल खाने वाली सभी समस्याएं वर्तमान में हल की जा रही हैं।',
    noActiveClaimed: 'कोई सक्रिय परियोजना नहीं है',
    noActiveClaimedDesc: 'आपके संस्थान ने अभी तक कोई चुनौती नहीं ली है। अनुकूलित चुनौतियां टैब में जाकर समस्या चुनें।',

    // Auth
    signInTab: 'साइन इन करें',
    createAccountTab: 'नया खाता बनाएं',
    emailOrPhone: 'ईमेल या फोन नंबर',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूल गए?',
    signInButton: 'पोर्टल में प्रवेश करें',
    registeringAs: 'पंजीकरण का प्रकार:',
    fullName: 'पूरा नाम',
    phoneNumber: 'फोन नंबर',
    emailAddress: 'ईमेल पता',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    completeRegistration: 'पंजीकरण पूर्ण करें'
  },

  kht: {
    // Khortha / Nagpuri Localized
    platformTitle: 'समस्यासेतु',
    platformSubtitle: 'समस्या से समाधान सेतु',
    sihBannerTitle: 'झारखंड SIH • समाजक समस्या आर समाधान पोर्टल',
    sihBannerSubtitle: 'गांव-घरक जनता, पंचायत आर कालेज-उद्योग के जोड़क सेतु',
    oneClickSwitcher: '1-क्लिक रोल बदलू',
    publicImpactWall: 'जनताक असर दीवार',
    myDashboard: 'हमार डैशबोर्ड',
    reportProblem: 'समस्या दर्ज करू',
    signIn: 'लागिन करू',
    register: 'खाता बनावू',
    logout: 'बाहर निकलू',
    selectLanguage: 'भाषा',

    heroTag: 'झारखंड सामाजिक नवाचार प्रभाव',
    heroTitle: 'गाँव-घरक समस्या के वैज्ञानिक समाधान में बदलना',
    heroSubtitle: 'गाँवक जनता आर पंचायत द्वारा उठल समस्या, हमर कालेज आर विद्यार्थी सब बनावत समाधान।',
    citizensBenefited: 'फायदा पावल जनता',
    problemsSolved: 'हल भेल समस्या',
    patentsFiled: 'पेटेंट दर्ज भेल',
    startupsIncubated: 'नवा स्टार्टअप बनल',
    verifiedImpactStories: 'सफल समाधानक कहानी',
    statewideExplorer: 'झारखंड समस्या नक्शा',
    deployedInnovation: 'जमीन पर लागल नवाचार',
    communityOutcome: 'गाँवक फायदा',
    citizensImpacted: 'फायदा पावल लोग',

    welcomeUser: 'जोहार',
    citizenPortalTag: 'नागरिक एवं समुदाय पोर्टल (झारखंड)',
    citizenPortalDesc: 'गाँव-टोलक चापाकल, सड़क, स्कूलक समस्या लिखू आर कालेजक टीम से समाधान पावू।',
    reportNewProblem: 'नवा समस्या दर्ज करू',
    trackMyReports: 'हमार समस्याक हाल देखू',
    myReportsLogged: 'हमार दर्ज समस्या',
    activeChallenges: 'चालू समस्या',
    solutionsInField: 'काम चलत समाधान',
    impactVerified: 'पूरा हल भेल',
    recentSocietalReports: 'हालक समस्या सब',
    sortedByPriority: 'जरूरी के हिसाब से',
    viewDetails: 'हालचाल देखू',
    confirmationsCount: 'लोगक समर्थन',
    proposalsCount: 'समाधान प्रस्ताव',
    noReportsYet: 'अखनी तक कोनो समस्या दर्ज नय भेल हे',
    noReportsYetDesc: 'अपन गाँव-टोलक कोनो समस्या दर्ज करू जेकर से कालेजक छात्र समाधान बनाई पावे।',
    reportFirstProblem: 'अपन पहिल समस्या दर्ज करू',
    progressLifecycle: 'काम के हालचाल',
    reportedOn: 'दर्ज करल तारीख',

    step1Title: '1. समस्याक विवरण आर भाषा',
    step2Title: '2. गाँव/टोलक जगह आर जीपीएस',
    step3Title: '3. फोटो / वीडियो सबूत',
    problemTitleLabel: 'समस्याक नाम / शीर्षक *',
    problemTitlePlaceholder: 'जैसे: चापाकल खराब हे / पुलिया बह गेल हे',
    problemDescLabel: 'खोरठा/नागपुरी/हिंदी में समस्याक पूरा बात लिखू *',
    problemDescPlaceholder: 'समस्याक पूरा बात लिखू, कतेक घर परेशान हे... (बोल के भी लिख सकू)',
    voiceToText: 'बोल के लिखू (वॉइस)',
    recordingVoice: 'आवाज रिकार्ड होत हे (बोलू)...',
    autoGps: 'हमर जीपीएस जगह अपने-आप लियू',
    districtLabel: 'जिला (झारखंड)',
    latitude: 'Latitude',
    longitude: 'Longitude',
    evidenceUpload: 'फोटो / वीडियो सबूत जोड़ू',
    uploadClickText: 'फोटो या वीडियो जोड़े ले क्लिक करू',
    uploadFormatsText: 'JPG, PNG, MP4 (10MB तक)',
    submitAndLaunchAI: 'समस्या भेजू आर जांच शुरू करू',
    iHaveThisProblemToo: 'हमारो ई समस्या हे (समर्थन करू)',
    confirmedBy: 'समर्थन मिलल',
    submitSolutionProposal: 'समाधान प्रस्ताव भेजू',
    englishTranslation: 'अंग्रेजी अनुवाद (एआई)',
    originalSubmission: 'गाँव से भेजल मूल शिकायत',
    aiPipelineInProgress: 'एआई जांच चलत हे: भाषा अनुवाद आर जरूरी स्कोर निकालल जा रहल हे...',

    reportedBy: 'भेजनिहार',
    solutionsAndProposals: 'कालेजक समाधान प्रस्ताव सब',
    noProposalsYet: 'अखनी कोनो प्रस्ताव नय आयल हे',
    noProposalsDesc: 'कालेज आर विद्यार्थी सब समाधान बनावत हे।',
    beFirstToSubmit: 'पहिल समाधान भेजू',
    techApproachLabel: 'तकनीकी तरीका आर बनावट',
    budgetLabel: 'अनुमानित बजट',
    timelineLabel: 'समय सीमा',
    csrFundingPledged: 'सीएसआर पैसा मिलल',
    problemLocation: 'समस्याक जगह',
    photoFieldEvidence: 'फोटो सबूत',
    aiMatchedInstitutions: 'मैच भेल कालेज सब',

    priorityEngine: 'प्राथमिकता स्कोर',
    criticalPriority: 'सबले जरूरी (Critical)',
    highPriority: 'भारी जरूरी (High)',
    mediumPriority: 'मध्यम (Medium)',
    lowPriority: 'साधारण (Low)',
    safetyRisk: 'खतरा / बीमारी रिस्क',
    citizenVolume: 'प्रभावित लोगक संख्या',
    schoolClinicProximity: 'स्कूल/अस्पताल बगले में',
    daysPending: 'कतेक दिन से रुकल हे',
    districtTier: 'जिला प्राथमिकता',
    scoreBreakdown: 'स्कोर के हिसाब:',
    auditTrail: 'कारण:',

    statusProcessing: 'एआई जांच चालु हे',
    statusPendingVerification: 'अफसर जांच बाकी हे',
    statusPublished: 'कालेज सबके भेजल गेल',
    statusClaimed: 'कालेज टीम काम लेलक',
    statusInDevelopment: 'काम चलत हे',
    statusDeployed: 'जमीन पर लग गेल',
    statusImpactVerified: 'समस्या पूरा हल भेल',
    statusRejected: 'रद्द भेल',
    statusMerged: 'डुप्लीकेट मिलावल गेल',

    adminCommandCenter: 'राज्य प्रशासनिक केंद्र • झारखंड',
    adminDesc: 'नागरिक रिपोर्ट देखू, खाता मंजूर करू आर राजकीय कामक निगरानी करू।',
    verificationQueueTab: 'जांच कतार',
    accountApprovalsTab: 'खाता मंजूरी',
    analyticsTab: 'राजकीय आंकड़ा',
    oneClickApprove: '1-क्लिक मंजूरी देऊ',
    reject: 'रद्द करू',
    approveAccount: 'खाता मंजूर करू',
    verificationQueueClear: 'जांच कतार खाली हे',
    verificationQueueClearDesc: 'सब समस्या जांच भ गेल हे।',
    noPendingAccounts: 'कोनो खाता बाकी नय हे',
    noPendingAccountsDesc: 'सब खाता मंजूर भ गेल हे।',

    heiPortalTag: 'कालेज एवं छात्र वैज्ञानिक नवाचार पोर्टल',
    heiDesc: 'अपन कालेजक हिसाब से समस्या देखू, टीम बनावू आर जमीन पर काम करू।',
    matchedChallengesTab: 'मैच भेल चुनौती',
    myProjectsTab: 'हमार प्रोजेक्ट एवं काम',
    claimAndPropose: 'ई समस्या लेवू आर समाधान बनावू',
    techApproach: 'तकनीकी तरीका *',
    techStack: 'उपयोग तकनीक (Tech Stack) *',
    estimatedBudget: 'लागत / बजट (₹ INR)',
    timelineWeeks: 'समय (सप्ताह)',
    milestonesRoadmap: 'काम के चरण (Roadmap)',
    logImpactAndIP: 'पेटेंट आर असर दर्ज करू',
    csrGrantPledge: 'सीएसआर पैसा व मदद देऊ',
    noMatchedOpen: 'कोनो चुनौती खाली नय हे',
    noMatchedOpenDesc: 'सब समस्या पर काम चलत हे।',
    noActiveClaimed: 'कोनो प्रोजेक्ट नय लेल गेल हे',
    noActiveClaimedDesc: 'मैच भेल चुनौती में जा के समस्या चुनू।',

    signInTab: 'लागिन करू',
    createAccountTab: 'नवा खाता बनावू',
    emailOrPhone: 'ईमेल या फोन नंबर',
    password: 'पासवर्ड',
    forgotPassword: 'पासवर्ड भूलाय गेला?',
    signInButton: 'पोर्टल में जावू',
    registeringAs: 'खाताक प्रकार:',
    fullName: 'पूरा नाम',
    phoneNumber: 'फोन नंबर',
    emailAddress: 'ईमेल पता',
    confirmPassword: 'पासवर्ड दोबारा लिखू',
    completeRegistration: 'खाता बनावू'
  },

  sat: {
    // Santhali / Tribal Localized
    platformTitle: 'SamasyaSetu (ᱥᱟᱢᱟᱥᱭᱟᱥᱮᱛᱩ)',
    platformSubtitle: 'ᱥᱟᱱᱛᱟᱲᱤ • Problem-to-Solution Platform',
    sihBannerTitle: 'ᱡᱷᱟᱨᱠᱷᱚᱸᱰ SIH • ᱥᱟᱢᱟᱡᱤᱠ ᱱᱟᱣᱟᱱᱟᱜ ᱜᱚᱲᱚ-ᱜᱚᱯᱚᱲᱚ ᱯᱚᱨᱴᱟᱞ',
    sihBannerSubtitle: 'ᱟᱹᱛᱩ-ᱴᱚᱞᱟ ᱨᱮᱱ ᱦᱚᱲ, ᱯᱟᱧᱪᱟᱭᱮᱛ ᱟᱨ ᱵᱤᱨᱫᱟᱹᱜᱟᱲ ᱠᱚ ᱡᱚᱲᱟᱣ',
    oneClickSwitcher: '1-Click ᱨᱚᱞ ᱵᱚᱫᱚᱞ',
    publicImpactWall: 'ᱨᱟᱡᱽ ᱥᱟᱢᱟᱡᱤᱠ ᱯᱨᱚᱵᱷᱟᱣ ᱠᱟᱸᱛ',
    myDashboard: 'ᱤᱧᱟᱜ ᱰᱮᱥᱵᱚᱨᱰ',
    reportProblem: 'ᱮᱴᱠᱮᱴᱚᱬᱮ ᱚᱞ ᱢᱮ (Report)',
    signIn: 'ᱞᱚᱜᱤᱱ',
    register: 'ᱮᱛᱚᱦᱚᱵ',
    logout: 'ᱵᱟᱦᱨᱮ ᱚᱰᱚᱠ',
    selectLanguage: 'ᱯᱟᱹᱨᱥᱤ (Language)',

    heroTag: 'ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱥᱟᱢᱟᱡᱤᱠ ᱱᱟᱣᱟ ᱦᱩᱫᱤᱥ',
    heroTitle: 'ᱟᱹᱛᱩ ᱨᱮᱱᱟᱜ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱥᱟᱬᱮᱥᱤᱭᱟᱹ ᱥᱚᱞᱦᱮ ᱨᱮ ᱵᱚᱫᱚᱞ',
    heroSubtitle: 'ᱟᱹᱛᱩ-ᱴᱚᱞᱟ ᱠᱷᱚᱱ ᱦᱮᱡ ᱟᱠᱟᱱ ᱫᱟᱜ, ᱰᱟᱦᱟᱨ, ᱨᱩᱣᱟᱹ-ᱦᱟᱹᱥᱩ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱠᱚ ᱤᱱᱡᱤᱱᱤᱭᱟᱨ ᱯᱟᱹᱴᱷᱩᱣᱟᱹ ᱠᱚ ᱥᱚᱞᱦᱮᱭᱟ᱾',
    citizensBenefited: 'ᱞᱟᱵᱷ ᱧᱟᱢ ᱦᱚᱲ',
    problemsSolved: 'ᱥᱚᱞᱦᱮ ᱟᱠᱟᱱ ᱠᱟᱹᱢᱤ',
    patentsFiled: 'ᱯᱮᱴᱮᱱᱴ (Patents)',
    startupsIncubated: 'ᱱᱟᱣᱟ ᱥᱴᱟᱨᱴᱟᱯ',
    verifiedImpactStories: 'ᱥᱟᱹᱨᱤ ᱟᱠᱟᱱ ᱱᱟᱯᱟᱭ ᱠᱟᱹᱦᱱᱤ',
    statewideExplorer: 'ᱯᱚᱱᱚᱛ ᱱᱚᱠᱥᱟ ᱧᱮᱞ',
    deployedInnovation: 'ᱴᱚᱞᱟ ᱨᱮ ᱵᱟᱹᱭᱥᱟᱹᱣ ᱮᱱᱟ',
    communityOutcome: 'ᱟᱹᱛᱩ ᱨᱮᱱᱟᱜ ᱚᱨᱡᱚ',
    citizensImpacted: 'ᱞᱟᱵᱷ ᱧᱟᱢ ᱦᱚᱲ',

    welcomeUser: 'ᱡᱚᱦᱟᱨ (Johar)',
    citizenPortalTag: 'ᱦᱚᱲ ᱟᱨ ᱟᱹᱛᱩ ᱯᱚᱨᱴᱟᱞ (Jharkhand)',
    citizenPortalDesc: 'ᱟᱢᱟᱜ ᱴᱚᱞᱟ ᱨᱮᱱᱟᱜ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱚᱞ ᱢᱮ ᱟᱨ ᱵᱤᱨᱫᱟᱹᱜᱟᱲ ᱠᱷᱚᱱ ᱥᱚᱞᱦᱮ ᱧᱟᱢ ᱢᱮ᱾',
    reportNewProblem: 'ᱱᱟᱣᱟ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱚᱞ ᱢᱮ',
    trackMyReports: 'ᱤᱧᱟᱜ ᱨᱤᱯᱚᱨᱴ ᱧᱮᱞ',
    myReportsLogged: 'ᱤᱧᱟᱜ ᱮᱢ ᱟᱠᱟᱱ ᱮᱴᱠᱮᱴᱚᱬᱮ',
    activeChallenges: 'ᱪᱟᱹᱞᱩ ᱮᱴᱠᱮᱴᱚᱬᱮ',
    solutionsInField: 'ᱠᱟᱹᱢᱤ ᱪᱟᱞᱟᱜ ᱠᱟᱱ ᱥᱚᱞᱦᱮ',
    impactVerified: 'ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ',
    recentSocietalReports: 'ᱱᱟᱦᱟᱜ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱠᱚ',
    sortedByPriority: 'ᱞᱟᱹᱠᱛᱤ ᱞᱮᱠᱟᱛᱮ',
    viewDetails: 'ᱯᱩᱨᱟᱹ ᱧᱮᱞ',
    confirmationsCount: 'ᱦᱚᱲ ᱥᱟᱹᱵᱩᱛ',
    proposalsCount: 'ᱥᱚᱞᱦᱮ ᱯᱨᱚᱯᱚᱡᱟᱞ',
    noReportsYet: 'ᱱᱤᱛ ᱫᱷᱟᱹᱵᱤᱡ ᱪᱮᱫ ᱦᱚᱸ ᱵᱟᱝ ᱮᱢ ᱟᱠᱟᱱᱟ',
    noReportsYetDesc: 'ᱟᱢᱟᱜ ᱴᱚᱞᱟ ᱨᱮᱱᱟᱜ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱚᱞ ᱢᱮ ᱡᱮᱢᱚᱱ ᱵᱤᱨᱫᱟᱹᱜᱟᱲ ᱨᱮᱱ ᱯᱟᱹᱴᱷᱩᱣᱟᱹ ᱠᱚ ᱥᱚᱞᱦᱮ ᱵᱮᱱᱟᱣ ᱫᱟᱲᱮᱭᱟᱜ-ᱟ᱾',
    reportFirstProblem: 'ᱯᱩᱭᱞᱩ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱚᱞ ᱢᱮ',
    progressLifecycle: 'ᱠᱟᱹᱢᱤ ᱞᱟᱦᱟᱱᱛᱤ',
    reportedOn: 'ᱮᱢ ᱟᱠᱟᱱ ᱢᱟᱹᱦᱤᱛ',

    step1Title: '1. ᱮᱴᱠᱮᱴᱚᱬᱮ ᱵᱤᱵᱚᱨᱚᱬ ᱟᱨ ᱯᱟᱹᱨᱥᱤ',
    step2Title: '2. ᱴᱚᱞᱟ ᱨᱮᱱᱟᱜ ᱡᱟᱭᱜᱟ ᱟᱨ GPS',
    step3Title: '3. ᱯᱷᱚᱴᱚ / ᱵᱷᱤᱰᱤᱭᱳ ᱥᱟᱹᱵᱩᱛ',
    problemTitleLabel: 'ᱮᱴᱠᱮᱴᱚᱬᱮ ᱧᱩᱛᱩᱢ *',
    problemTitlePlaceholder: 'ᱡᱮᱞᱮᱠᱟ: ᱪᱟᱯᱟᱠᱚᱞ ᱨᱟᱹᱯᱩᱫ ᱟᱠᱟᱱᱟ / ᱥᱟᱸᱠᱳ ᱵᱟᱹᱱᱩᱜ-ᱟ',
    problemDescLabel: 'ᱥᱟᱱᱛᱟᱲᱤ/ᱦᱤᱱᱫᱤ/ᱤᱝᱞᱤᱥ ᱛᱮ ᱯᱩᱨᱟᱹ ᱵᱤᱵᱚᱨᱚᱬ ᱚᱞ ᱢᱮ *',
    problemDescPlaceholder: 'ᱮᱴᱠᱮᱴᱚᱬᱮ ᱵᱟᱵᱚᱛ ᱚᱞ ᱢᱮ, ᱛᱤᱱᱟᱹᱜ ᱦᱚᱲ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱨᱮ ᱢᱮᱱᱟᱜ ᱠᱚᱣᱟ... (ᱨᱚᱲ ᱠᱟᱛᱮ ᱦᱚᱸ ᱚᱞ ᱜᱟᱱᱚᱜ-ᱟ)',
    voiceToText: 'ᱨᱚᱲ ᱠᱟᱛᱮ ᱚᱞ ᱢᱮ (Voice)',
    recordingVoice: 'ᱟᱲᱟᱝ ᱨᱮᱠᱚᱨᱰᱚᱜ ᱠᱟᱱᱟ (ᱨᱚᱲ ᱢᱮ)...',
    autoGps: 'GPS ᱡᱟᱭᱜᱟ ᱚᱴᱚ ᱦᱟᱛᱟᱣ',
    districtLabel: 'ᱡᱤᱞᱟᱹ (District)',
    latitude: 'Latitude',
    longitude: 'Longitude',
    evidenceUpload: 'ᱯᱷᱚᱴᱚ / ᱵᱷᱤᱰᱤᱭᱳ ᱥᱟᱹᱵᱩᱛ',
    uploadClickText: 'ᱯᱷᱚᱴᱚ ᱵᱷᱤᱰᱤᱭᱳ ᱮᱢ ᱞᱟᱹᱜᱤᱫ ᱚᱛᱟᱭ ᱢᱮ',
    uploadFormatsText: 'JPG, PNG, MP4 (10MB ᱦᱟᱹᱵᱤᱡ)',
    submitAndLaunchAI: 'ᱮᱢ ᱢᱮ ᱟᱨ AI ᱡᱟᱸᱪ ᱮᱦᱚᱵ',
    iHaveThisProblemToo: 'ᱤᱧᱟᱜ ᱦᱚᱸ ᱱᱚᱣᱟ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱢᱮᱱᱟᱜ-ᱟ',
    confirmedBy: 'ᱥᱟᱹᱵᱩᱛ ᱮᱱᱟ',
    submitSolutionProposal: 'ᱥᱚᱞᱦᱮ ᱯᱨᱚᱯᱚᱡᱟᱞ ᱮᱢ',
    englishTranslation: 'English Translation (AI)',
    originalSubmission: 'ᱢᱩᱬᱩᱛ ᱴᱚᱞᱟ ᱨᱮᱱᱟᱜ ᱚᱞ',
    aiPipelineInProgress: 'AI ᱡᱟᱸᱪ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ: ᱯᱟᱹᱨᱥᱤ ᱛᱚᱨᱡᱚᱢᱟ ᱟᱨ ᱞᱟᱹᱠᱛᱤ ᱥᱠᱳᱨ ᱵᱮᱱᱟᱣᱜ ᱠᱟᱱᱟ...',

    reportedBy: 'ᱚᱞ ᱟᱠᱟᱫ ᱦᱚᱲ',
    solutionsAndProposals: 'ᱵᱤᱨᱫᱟᱹᱜᱟᱲ ᱥᱚᱞᱦᱮ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ',
    noProposalsYet: 'ᱱᱤᱛ ᱫᱷᱟᱹᱵᱤᱡ ᱥᱚᱞᱦᱮ ᱵᱟᱝ ᱦᱮᱡ ᱟᱠᱟᱱᱟ',
    noProposalsDesc: 'ᱵᱤᱨᱫᱟᱹᱜᱟᱲ ᱟᱨ ᱯᱟᱹᱴᱷᱩᱣᱟᱹ ᱠᱚ ᱥᱚᱞᱦᱮ ᱵᱮᱱᱟᱣ ᱨᱮ ᱢᱮᱱᱟᱜ ᱠᱚᱣᱟ᱾',
    beFirstToSubmit: 'ᱯᱩᱭᱞᱩ ᱥᱚᱞᱦᱮ ᱮᱢ ᱢᱮ',
    techApproachLabel: 'ᱴᱮᱠᱱᱤᱠᱟᱞ ᱩᱯᱟᱹᱭ',
    budgetLabel: 'ᱵᱟᱡᱮᱴ (Budget)',
    timelineLabel: 'ᱚᱠᱛᱚ (Timeline)',
    csrFundingPledged: 'CSR ᱜᱚᱲᱚ ᱯᱩᱭᱥᱟᱹ',
    problemLocation: 'ᱮᱴᱠᱮᱴᱚᱬᱮ ᱡᱟᱭᱜᱟ',
    photoFieldEvidence: 'ᱯᱷᱚᱴᱚ ᱥᱟᱹᱵᱩᱛ',
    aiMatchedInstitutions: 'ᱢᱮᱪ ᱟᱠᱟᱱ ᱵᱤᱨᱫᱟᱹᱜᱟᱲ',

    priorityEngine: 'ᱞᱟᱹᱠᱛᱤ ᱥᱠᱳᱨ (Priority)',
    criticalPriority: 'ᱟᱹᱰᱤ ᱡᱟᱹᱨᱩᱨ (Critical)',
    highPriority: 'ᱡᱟᱹᱨᱩᱨ (High)',
    mediumPriority: 'ᱛᱟᱞᱟᱢᱟᱞᱟ (Medium)',
    lowPriority: 'ᱥᱟᱫᱷᱟᱨᱚᱱ (Low)',
    safetyRisk: 'ᱵᱤᱯᱚᱫᱽ / ᱦᱟᱹᱥᱩ ᱨᱤᱥᱠ',
    citizenVolume: 'ᱦᱚᱲ ᱮᱞ',
    schoolClinicProximity: 'ᱟᱥᱲᱟ/ᱦᱟᱥᱯᱟᱛᱟᱞ ᱥᱩᱨ',
    daysPending: 'ᱛᱤᱱᱟᱹᱜ ᱫᱤᱱ ᱦᱩᱭ ᱮᱱᱟ',
    districtTier: 'ᱡᱤᱞᱟᱹ ᱢᱟᱹᱱ',
    scoreBreakdown: 'ᱥᱠᱳᱨ ᱞᱮᱠᱷᱟ:',
    auditTrail: 'ᱠᱟᱨᱚᱱ:',

    statusProcessing: 'AI ᱡᱟᱸᱪ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ',
    statusPendingVerification: 'ᱚᱯᱷᱤᱥᱟᱨ ᱡᱟᱸᱪ ᱵᱟᱹᱠᱤ',
    statusPublished: 'ᱥᱚᱞᱦᱮ ᱞᱟᱹᱜᱤᱫ ᱡᱷᱤᱡ ᱮᱱᱟ',
    statusClaimed: 'ᱠᱚᱞᱮᱡᱽ ᱴᱤᱢ ᱮ ᱦᱟᱛᱟᱣ ᱠᱮᱫᱟ',
    statusInDevelopment: 'ᱠᱟᱹᱢᱤ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ',
    statusDeployed: 'ᱴᱚᱞᱟ ᱨᱮ ᱵᱟᱹᱭᱥᱟᱹᱣ ᱮᱱᱟ',
    statusImpactVerified: 'ᱥᱚᱞᱦᱮ ᱯᱩᱨᱟᱹᱣ ᱮᱱᱟ',
    statusRejected: 'ᱵᱟᱹᱛᱤᱞ ᱮᱱᱟ',
    statusMerged: 'ᱢᱮᱥᱟ ᱮᱱᱟ',

    adminCommandCenter: 'ᱯᱚᱱᱚᱛ ᱥᱟᱥᱚᱱ ᱛᱟᱞᱢᱟ • Jharkhand',
    adminDesc: 'ᱮᱴᱠᱮᱴᱚᱬᱮ ᱡᱟᱸᱪ ᱢᱮ, ᱮᱠᱟᱣᱩᱱᱴ ᱢᱟᱹᱱ ᱮᱢ ᱢᱮ ᱟᱨ ᱠᱟᱹᱢᱤ ᱧᱮᱞ ᱢᱮ᱾',
    verificationQueueTab: 'ᱡᱟᱸᱪ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ',
    accountApprovalsTab: 'ᱮᱠᱟᱣᱩᱱᱴ ᱢᱟᱹᱱ',
    analyticsTab: 'ᱯᱚᱱᱚᱛ ᱞᱮᱠᱷᱟ-ᱡᱚᱠᱷᱟ',
    oneClickApprove: '1-Click ᱢᱟᱹᱱ ᱮᱢ',
    reject: 'ᱵᱟᱹᱛᱤᱞ',
    approveAccount: 'ᱮᱠᱟᱣᱩᱱᱴ ᱢᱟᱹᱱ',
    verificationQueueClear: 'ᱡᱟᱸᱪ ᱠᱟᱹᱢᱤᱦᱚᱨᱟ ᱯᱷᱟᱸᱠᱟ ᱜᱮᱭᱟ',
    verificationQueueClearDesc: 'ᱥᱟᱱᱟᱢ ᱨᱤᱯᱚᱨᱴ ᱡᱟᱸᱪ ᱟᱠᱟᱱᱟ᱾',
    noPendingAccounts: 'ᱠᱚᱱᱚ ᱮᱠᱟᱣᱩᱱᱴ ᱵᱟᱹᱠᱤ ᱵᱟᱹᱱᱩᱜ-ᱟ',
    noPendingAccountsDesc: 'ᱥᱟᱱᱟᱢ ᱮᱠᱟᱣᱩᱱᱴ ᱢᱟᱹᱱ ᱮᱢ ᱟᱠᱟᱱᱟ᱾',

    heiPortalTag: 'ᱵᱤᱨᱫᱟᱹᱜᱟᱲ ᱟᱨ ᱯᱟᱹᱴᱷᱩᱣᱟᱹ ᱱᱟᱣᱟ ᱦᱩᱫᱤᱥ ᱯᱚᱨᱴᱟᱞ',
    heiDesc: 'ᱵᱤᱨᱫᱟᱹᱜᱟᱲ ᱞᱮᱠᱟᱛᱮ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱧᱮᱞ ᱢᱮ, ᱴᱤᱢ ᱵᱮᱱᱟᱣ ᱢᱮ ᱟᱨ ᱠᱟᱹᱢᱤ ᱢᱮ᱾',
    matchedChallengesTab: 'ᱢᱮᱪ ᱟᱠᱟᱱ ᱪᱩᱱᱳᱛᱤ',
    myProjectsTab: 'ᱤᱧᱟᱜ ᱠᱟᱹᱢᱤ ᱟᱨ ᱯᱨᱚᱡᱮᱠᱴ',
    claimAndPropose: 'ᱱᱚᱣᱟ ᱠᱟᱹᱢᱤ ᱦᱟᱛᱟᱣ ᱢᱮ ᱟᱨ ᱥᱚᱞᱦᱮ ᱵᱮᱱᱟᱣ ᱢᱮ',
    techApproach: 'ᱴᱮᱠᱱᱤᱠᱟᱞ ᱩᱯᱟᱹᱭ *',
    techStack: 'ᱴᱮᱠ ᱥᱴᱮᱠ *',
    estimatedBudget: 'ᱵᱟᱡᱮᱴ (₹ INR)',
    timelineWeeks: 'ᱚᱠᱛᱚ (ᱦᱟᱯᱛᱟ)',
    milestonesRoadmap: 'ᱠᱟᱹᱢᱤ ᱨᱮᱱᱟᱜ ᱫᱷᱟᱯ (Roadmap)',
    logImpactAndIP: 'ᱯᱮᱴᱮᱱᱴ ᱟᱨ ᱚᱨᱡᱚ ᱚᱞ',
    csrGrantPledge: 'CSR ᱜᱚᱲᱚ ᱯᱩᱭᱥᱟᱹ ᱮᱢ',
    noMatchedOpen: 'ᱠᱚᱱᱚ ᱠᱟᱹᱢᱤ ᱠᱷᱟᱹᱞᱤ ᱵᱟᱹᱱᱩᱜ-ᱟ',
    noMatchedOpenDesc: 'ᱥᱟᱱᱟᱢ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱨᱮ ᱠᱟᱹᱢᱤ ᱪᱟᱞᱟᱜ ᱠᱟᱱᱟ᱾',
    noActiveClaimed: 'ᱠᱚᱱᱚ ᱯᱨᱚᱡᱮᱠᱴ ᱵᱟᱝ ᱦᱟᱛᱟᱣ ᱟᱠᱟᱱᱟ',
    noActiveClaimedDesc: 'ᱢᱮᱪ ᱟᱠᱟᱱ ᱪᱩᱱᱳᱛᱤ ᱠᱷᱚᱱ ᱮᱴᱠᱮᱴᱚᱬᱮ ᱵᱟᱪᱷᱟᱣ ᱢᱮ᱾',

    signInTab: 'ᱞᱚᱜᱤᱱ',
    createAccountTab: 'ᱱᱟᱣᱟ ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ',
    emailOrPhone: 'ᱤᱢᱮᱞ ᱵᱟᱝᱠᱷᱟᱱ ᱯᱷᱳᱱ ᱱᱚᱢᱵᱚᱨ',
    password: 'ᱯᱟᱥᱣᱟᱨᱰ',
    forgotPassword: 'ᱯᱟᱥᱣᱟᱨᱰ ᱦᱤᱲᱤᱧ ᱮᱱᱟ?',
    signInButton: 'ᱯᱚᱨᱴᱟᱞ ᱨᱮ ᱵᱚᱞᱚᱱ',
    registeringAs: 'ᱮᱠᱟᱣᱩᱱᱴ ᱞᱮᱠᱟᱱ:',
    fullName: 'ᱯᱩᱨᱟᱹ ᱧᱩᱛᱩᱢ',
    phoneNumber: 'ᱯᱷᱳᱱ ᱱᱚᱢᱵᱚᱨ',
    emailAddress: 'ᱤᱢᱮᱞ ᱴᱷᱤᱠᱬᱟᱹ',
    confirmPassword: 'ᱯᱟᱥᱣᱟᱨᱰ ᱫᱚᱦᱲᱟ ᱚᱞ',
    completeRegistration: 'ᱮᱠᱟᱣᱩᱱᱴ ᱵᱮᱱᱟᱣ'
  },

  bn: {
    // Bengali Localized
    platformTitle: 'সমস্যাসেতু',
    platformSubtitle: 'সমস্যা থেকে সমাধান পোর্টাল',
    sihBannerTitle: 'ঝাড়খণ্ড এসআইএইচ সংস্করণ • সামাজিক উদ্ভাবন সহযোগিতা পোর্টাল',
    sihBannerSubtitle: 'নাগরিক ও পঞ্চায়েতকে বিশ্ববিদ্যালয় ও শিল্পের সাথে সংযুক্ত করা',
    oneClickSwitcher: '১-ক্লিক রোল পরিবর্তন',
    publicImpactWall: 'পাবলিক ইমপ্যাক্ট ওয়াল',
    myDashboard: 'আমার ড্যাশবোর্ড',
    reportProblem: 'সমস্যা নথিভুক্ত করুন',
    signIn: 'লগ ইন',
    register: 'শুরু করুন',
    logout: 'লগ আউট',
    selectLanguage: 'ভাষা',

    heroTag: 'ঝাড়খণ্ড সামাজিক উদ্ভাবন প্রভাব',
    heroTitle: 'নাগরিক সমস্যাকে বাস্তব উদ্ভাবনে রূপান্তর',
    heroSubtitle: 'নাগরিকদের সমস্যা বিশ্ববিদ্যালয় গবেষক এবং স্টার্টআপ দ্বারা সমাধান করা হয়।',
    citizensBenefited: 'উপকৃত নাগরিক',
    problemsSolved: 'সমাধানকৃত সমস্যা',
    patentsFiled: 'নিবন্ধিত পেটেন্ট',
    startupsIncubated: 'ইনকিউবেটেড স্টার্টআপ',
    verifiedImpactStories: 'যাচাইকৃত সফলতার গল্প',
    statewideExplorer: 'রাজ্যব্যাপী মানচিত্র এক্সপ্লোরার',
    deployedInnovation: 'বাস্তবায়িত উদ্ভাবন',
    communityOutcome: 'সামাজিক ফলাফল',
    citizensImpacted: 'উপকৃত নাগরিক',

    welcomeUser: 'স্বাগতম',
    citizenPortalTag: 'নাগরিক ও সম্প্রদায় পোর্টাল (ঝাড়খণ্ড SIH)',
    citizenPortalDesc: 'আপনার এলাকার সমস্যা রিপোর্ট করুন এবং বিশ্ববিদ্যালয় ও স্টার্টআপদের সাথে যুক্ত হন।',
    reportNewProblem: 'নতুন সমস্যা রিপোর্ট করুন',
    trackMyReports: 'আমার রিপোর্টগুলি দেখুন',
    myReportsLogged: 'মোট রিপোর্ট',
    activeChallenges: 'সক্রিয় চ্যালেঞ্জ',
    solutionsInField: 'চলমান সমাধান',
    impactVerified: 'যাচাইকৃত সমাধান',
    recentSocietalReports: 'সাম্প্রতিক সামাজিক সমস্যা',
    sortedByPriority: 'অগ্রাধিকার অনুযায়ী সাজানো',
    viewDetails: 'বিস্তারিত দেখুন',
    confirmationsCount: 'নাগরিক সমর্থন',
    proposalsCount: 'প্রস্তাবনা',
    noReportsYet: 'কোনো সমস্যা নথিভুক্ত হয়নি',
    noReportsYetDesc: 'আপনি এখনও কোনো সমস্যা জমা দেননি। আপনার এলাকার সমস্যা জমা দিন।',
    reportFirstProblem: 'প্রথম সমস্যা নথিভুক্ত করুন',
    progressLifecycle: 'কাজের অগ্রগতি',
    reportedOn: 'নথিভুক্তের তারিখ',

    step1Title: '১. সমস্যার বিবরণ ও ভাষা সহায়তা',
    step2Title: '২. অবস্থান এবং জিপিএস স্থানাঙ্ক',
    step3Title: '৩. ছবি / ভিডিও প্রমাণ এবং নথি',
    problemTitleLabel: 'সমস্যার শিরোনাম *',
    problemTitlePlaceholder: 'যেমন: নলকূপে আর্সেনিক সমস্যা / ভাঙা কালভার্ট',
    problemDescLabel: 'বিস্তারিত বিবরণ (বাংলা, হিন্দি বা ইংরেজিতে) *',
    problemDescPlaceholder: 'সমস্যার বিবরণ, ক্ষতিগ্রস্ত পরিবারের সংখ্যা লিখুন... (ভয়েস দিয়েও বলতে পারেন)',
    voiceToText: 'ভয়েস দিয়ে লিখুন',
    recordingVoice: 'ভয়েস রেকর্ড হচ্ছে (এখন কথা বলুন)...',
    autoGps: 'স্বয়ংক্রিয় জিপিএস অবস্থান নিন',
    districtLabel: 'জেলা (ঝাড়খণ্ড)',
    latitude: 'অক্ষাংশ (Latitude)',
    longitude: 'দ্রাঘিমাংশ (Longitude)',
    evidenceUpload: 'ছবি / ভিডিও প্রমাণ এবং নথি',
    uploadClickText: 'ছবি বা ভিডিও আপলোড করতে ক্লিক করুন',
    uploadFormatsText: 'JPG, PNG, MP4 (10MB পর্যন্ত)',
    submitAndLaunchAI: 'সমস্যা জমা দিন ও এআই বিশ্লেষণ শুরু করুন',
    iHaveThisProblemToo: 'আমারও এই সমস্যা আছে',
    confirmedBy: 'নিশ্চিত করেছেন',
    submitSolutionProposal: 'সমাধানের প্রস্তাব জমা দিন',
    englishTranslation: 'ইংরেজি অনুবাদ (AI)',
    originalSubmission: 'মূল স্থানীয় রিপোর্ট',
    aiPipelineInProgress: 'এআই প্রসেসিং চলছে: অনুবাদ ও অগ্রাধিকার স্কোর তৈরি হচ্ছে...',

    reportedBy: 'প্রতিবেদক',
    solutionsAndProposals: 'বিশ্ববিদ্যালয় সমাধান প্রস্তাবনা',
    noProposalsYet: 'এখনও কোনো প্রস্তাব আসেনি',
    noProposalsDesc: 'এই সমস্যাটি বর্তমানে বিশ্ববিদ্যালয় ও স্টার্টআপদের জন্য উন্মুক্ত।',
    beFirstToSubmit: 'প্রথম প্রস্তাব জমা দিন',
    techApproachLabel: 'প্রযুক্তিগত পদ্ধতি ও কাঠামো',
    budgetLabel: 'আনুমানিক বাজেট',
    timelineLabel: 'সময়সীমা',
    csrFundingPledged: 'সিএসআর অনুদান গৃহীত',
    problemLocation: 'সমস্যার অবস্থান',
    photoFieldEvidence: 'ছবি ও প্রমাণ',
    aiMatchedInstitutions: 'ম্যাচ করা প্রতিষ্ঠান',

    priorityEngine: 'ব্যাখ্যাযোগ্য অগ্রাধিকার স্কোর',
    criticalPriority: 'জরুরি অগ্রাধিকার (Critical)',
    highPriority: 'উচ্চ অগ্রাধিকার (High)',
    mediumPriority: 'মাঝারি অগ্রাধিকার (Medium)',
    lowPriority: 'সাধারণ অগ্রাধিকার (Low)',
    safetyRisk: 'নিরাপত্তা / স্বাস্থ্য ঝুঁকি',
    citizenVolume: 'প্রভাবিত নাগরিক সংখ্যা',
    schoolClinicProximity: 'স্কুল/হাসপাতালের নৈকট্য',
    daysPending: 'কত দিন ধরে অমীমাংসিত',
    districtTier: 'জেলা অগ্রাধিকার স্তর',
    scoreBreakdown: 'স্কোর গঠন বিবরণ:',
    auditTrail: 'নিরীক্ষা ট্রেইল:',

    statusProcessing: 'এআই প্রসেসিং চলছে',
    statusPendingVerification: 'প্রশাসনিক যাচাই অপেক্ষমাণ',
    statusPublished: 'সমাধানের জন্য উন্মুক্ত',
    statusClaimed: 'সমাধান প্রস্তাবিত',
    statusInDevelopment: 'উন্নয়ন চলছে',
    statusDeployed: 'মাঠে কার্যকর',
    statusImpactVerified: 'সম্পূর্ণ সমাধানকৃত',
    statusRejected: 'প্রত্যাখ্যাত',
    statusMerged: 'ডুপ্লিকেট মার্জ হয়েছে',

    adminCommandCenter: 'রাজ্য প্রশাসনিক কমান্ড সেন্টার • ঝাড়খণ্ড',
    adminDesc: 'নাগরিকদের রিপোর্ট পর্যালোচনা করুন, প্রশাসনিক অ্যাকাউন্ট অনুমোদন করুন এবং রাজ্যব্যাপী প্রকল্প পর্যবেক্ষণ করুন।',
    verificationQueueTab: 'সমস্যা যাচাই সারি',
    accountApprovalsTab: 'বিভাগীয় অ্যাকাউন্ট অনুমোদন',
    analyticsTab: 'রাজ্যব্যাপী বিশ্লেষণ',
    oneClickApprove: '১-ক্লিকে অনুমোদন ও প্রকাশ করুন',
    reject: 'প্রত্যাখ্যান করুন',
    approveAccount: 'অ্যাকাউন্ট অনুমোদন করুন',
    verificationQueueClear: 'যাচাই সারি সম্পূর্ণ খালি',
    verificationQueueClearDesc: 'সমস্ত নাগরিক রিপোর্ট যাচাই করা হয়েছে।',
    noPendingAccounts: 'কোনো অ্যাকাউন্ট অপেক্ষমাণ নেই',
    noPendingAccountsDesc: 'সমস্ত প্রশাসনিক অ্যাকাউন্ট যাচাই করা হয়েছে।',

    heiPortalTag: 'উচ্চ শিক্ষা প্রতিষ্ঠান ও ছাত্র উদ্ভাবন পোর্টাল',
    heiDesc: 'আপনার প্রতিষ্ঠানের দক্ষতা অনুযায়ী সমস্যাগুলি অন্বেষণ করুন এবং ছাত্র দল গঠন করুন।',
    matchedChallengesTab: 'ম্যাচ করা চ্যালেঞ্জ',
    myProjectsTab: 'আমার প্রকল্প ও মাইলফলক',
    claimAndPropose: 'চ্যালেঞ্জ গ্রহণ করুন ও প্রস্তাব দিন',
    techApproach: 'প্রযুক্তিগত পদ্ধতি ও স্থাপত্য *',
    techStack: 'ব্যবহারযোগ্য প্রযুক্তি (Tech Stack) *',
    estimatedBudget: 'আনুমানিক বাজেট (₹ INR)',
    timelineWeeks: 'সময়সীমা (সপ্তাহ)',
    milestonesRoadmap: 'প্রকল্পের মাইলফলক রোডম্যাপ',
    logImpactAndIP: 'পেটেন্ট ও প্রভাব সংরক্ষণ করুন',
    csrGrantPledge: 'সিএসআর অনুদান ও পরামর্শ প্রদান',
    noMatchedOpen: 'কোনো উন্মুক্ত চ্যালেঞ্জ নেই',
    noMatchedOpenDesc: 'আপনার বিভাগের সাথে সম্পর্কিত সমস্ত সমস্যার সমাধান চলছে।',
    noActiveClaimed: 'কোনো প্রকল্প গ্রহণ করা হয়নি',
    noActiveClaimedDesc: 'ম্যাচ করা চ্যালেঞ্জ ট্যাব থেকে সমস্যা নির্বাচন করুন।',

    signInTab: 'লগ ইন',
    createAccountTab: 'নতুন অ্যাকাউন্ট তৈরি',
    emailOrPhone: 'ইমেল বা ফোন নম্বর',
    password: 'পাসওয়ার্ড',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    signInButton: 'পোর্টাল প্রবেশ করুন',
    registeringAs: 'নিবন্ধনের ধরন:',
    fullName: 'সম্পূর্ণ নাম',
    phoneNumber: 'ফোন নম্বর',
    emailAddress: 'ইমেল ঠিকানা',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    completeRegistration: 'নিবন্ধন সম্পন্ন করুন'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('samasyasetu_lang') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('samasyasetu_lang', lang);
  }, [lang]);

  const t = (key) => {
    const langDict = TRANSLATIONS[lang] || TRANSLATIONS.en;
    return langDict[key] || TRANSLATIONS.en[key] || key;
  };

  const currentLangObj = SUPPORTED_LANGUAGES.find(l => l.code === lang) || SUPPORTED_LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, supportedLanguages: SUPPORTED_LANGUAGES, currentLangObj }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
